// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"bookstack/cmd/service2/internal/controller.go"
	"bookstack/cmd/service2/internal/repository"
	"bookstack/cmd/service2/internal/service"
	"bookstack/config"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	db := config.ConnectDB(configConfig)
	shipperRepository := repository.NewShipperRepository(db)
	shipperOrderManageService := service.NewOrderManageService(shipperRepository)
	shipperController := controller.NewShipperController(shipperOrderManageService)
	app := &App{
		ShipperController: shipperController,
	}
	return app, nil
}

// injector.go:

var AppSet = wire.NewSet(config.LoadConfig, config.ConnectDB, RepositorySet,
	ServiceSet,
	ControllerSet, wire.Struct(new(App), "*"),
)

type App struct {
	ShipperController *controller.ShipperController
}
